services:
  db:
    image: postgres:16
    container_name: university-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: university_db
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: university-web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      # Map host socket to the standard location inside the container
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DB_CONTAINER_NAME=university-db
    depends_on:
      - db